import React from 'react';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Allgemeine Geschäftsbedingungen | Goldy Solar GmbH',
  description: 'Allgemeine Geschäftsbedingungen (AGB) der Goldy Solar GmbH',
};

export default function AGBPage() {
  return (
    <div className="container" style={{ paddingTop: '80px', paddingBottom: '100px', maxWidth: '800px' }}>
      <h1 style={{ fontSize: '36px', fontWeight: 900, marginBottom: '40px', color: '#0F4761' }}>Allgemeine Geschäftsbedingungen (AGB)</h1>
      
      <div style={{ fontSize: '16px', lineHeight: 1.8, color: '#404040' }}>
        <h2 style={{ fontSize: '28px', fontWeight: 900, marginTop: '60px', marginBottom: '20px', color: '#0F4761' }}>Allgemeine Geschäftsbedingungen für Verbraucher (B2C)</h2>
        <p style={{ fontSize: '18px', fontWeight: 700, marginBottom: '30px', color: '#4285F4' }}>für Planung, Kauf, Lieferung und Montage von Photovoltaikanlagen, Batteriespeichern und Wallboxen</p>
        <h3 style={{ fontSize: '22px', fontWeight: 800, marginTop: '40px', marginBottom: '12px', color: '#0E2841' }}>§ 1 Geltungsbereich und Vertragspartner</h3>
        <p style={{ fontSize: '13px', fontStyle: 'italic', color: '#64748B', marginBottom: '16px' }}>(Rechtsgrundlage: § 13 BGB, §§ 305 ff. BGB)</p>
        <p style={{ marginBottom: '16px' }}>Diese Allgemeinen Geschäftsbedingungen gelten für alle Verträge über die Planung, den Verkauf, die Lieferung und die fachgerechte Montage von Photovoltaikanlagen, Speichersystemen, Wallboxen sowie Zubehör zwischen der Goldy Solar GmbH (nachfolgend „Auftragnehmer“) und dem Kunden als Verbraucher (nachfolgend „Auftraggeber“).</p>
        <p style={{ marginBottom: '16px' }}>Verbraucher im Sinne dieser Geschäftsbedingungen ist jede natürliche Person, die das Rechtsgeschäft zu Zwecken abschließt, die überwiegend weder ihrer gewerblichen noch ihrer selbständigen beruflichen Tätigkeit zugerechnet werden können (§ 13 BGB).</p>
        <p style={{ marginBottom: '16px' }}>Entgegenstehende oder von diesen Bedingungen abweichende Vereinbarungen werden nur dann Vertragsbestandteil, wenn der Auftragnehmer ihnen ausdrücklich in Textform zugestimmt hat (§ 305b BGB).</p>
        <h3 style={{ fontSize: '22px', fontWeight: 800, marginTop: '40px', marginBottom: '12px', color: '#0E2841' }}>§ 2 Angebot, Vertragsschluss und Wirtschaftlichkeitsberechnungen</h3>
        <p style={{ fontSize: '13px', fontStyle: 'italic', color: '#64748B', marginBottom: '16px' }}>(Rechtsgrundlage: §§ 145 ff. BGB, § 312i BGB)</p>
        <p style={{ marginBottom: '16px' }}>Die Präsentationen von Produkten und Montagedienstleistungen auf der Website, in Werbematerialien oder in Online-Rechnern stellen kein bindendes Vertragsangebot dar, sondern eine unverbindliche Aufforderung zur Abgabe einer Anfrage durch den Kunden (invitatio ad offerendum).</p>
        <p style={{ marginBottom: '16px' }}>Der Vertrag kommt zustande, wenn der Auftraggeber das ihm nach Prüfung übersandte verbindliche Angebot des Auftragnehmers innerhalb der darin genannten Annahmefrist (im Zweifel 14 Tage ab Angebotsdatum gemäß § 148 BGB) in Textform annimmt oder der Auftragnehmer den Auftrag schriftlich bestätigt.</p>
        <p style={{ marginBottom: '16px' }}>Vorab durchgeführte Ertragsprognosen oder Simulationsrechnungen basieren auf standardisierten Softwaremodellen und historischen Wetterdaten. Sie stellen keine rechtlich bindende Beschaffenheits- oder Ertragsgarantie im Sinne des § 443 BGB dar.</p>
        <h3 style={{ fontSize: '22px', fontWeight: 800, marginTop: '40px', marginBottom: '12px', color: '#0E2841' }}>§ 3 Umsatzsteuerbefreiung (Nullsteuersatz)</h3>
        <p style={{ fontSize: '13px', fontStyle: 'italic', color: '#64748B', marginBottom: '16px' }}>(Rechtsgrundlage: § 12 Abs. 3 UStG)</p>
        <p style={{ marginBottom: '16px' }}>Für die Lieferung und Montage von Photovoltaikanlagen sowie wesentlichen Speicher- und Systemkomponenten an den Auftraggeber gilt der gesetzliche Nullsteuersatz (0 % Umsatzsteuer), sofern die Voraussetzungen des § 12 Abs. 3 Nr. 1 und Nr. 4 UStG erfüllt sind.</p>
        <p style={{ marginBottom: '16px' }}>Der Auftraggeber versichert mit Vertragsschluss, dass:</p>
        <p style={{ marginBottom: '16px' }}>er der Betreiber der Photovoltaikanlage ist,</p>
        <p style={{ marginBottom: '16px' }}>die installierte Bruttoleistung der Anlage laut Marktstammdatenregister (MaStR) nicht mehr als 30 kW (peak) beträgt oder betragen wird, oder</p>
        <p style={{ marginBottom: '16px' }}>die Anlage auf oder in der Nähe von Privatwohnungen, Wohnungen sowie öffentlichen oder anderen Gebäuden installiert wird, die für dem Gemeinwohl dienende Tätigkeiten genutzt werden.</p>
        <p style={{ marginBottom: '16px' }}>Sollte sich im Rahmen einer finanzamtlichen Überprüfung herausstellen, dass die Voraussetzungen des § 12 Abs. 3 UStG nicht vorlagen oder falsche Erklärungen abgegeben wurden, ist der Auftragnehmer berechtigt und verpflichtet, die reguläre gesetzliche Umsatzsteuer (derzeit 19 %) nachzuberechnen. Der Betrag ist binnen 14 Tagen nach Zugang der berichtigten Rechnung fällig.</p>
        <h3 style={{ fontSize: '22px', fontWeight: 800, marginTop: '40px', marginBottom: '12px', color: '#0E2841' }}>§ 4 Zahlungsbedingungen und Fälligkeiten</h3>
        <p style={{ fontSize: '13px', fontStyle: 'italic', color: '#64748B', marginBottom: '16px' }}>(Rechtsgrundlage: § 632a BGB, § 286 BGB, § 288 Abs. 1 BGB)</p>
        <p style={{ marginBottom: '16px' }}>Sofern im Einzelvertrag keine abweichende Abschlagszahlungsvereinbarung getroffen wurde, erfolgt die Abrechnung nach folgenden Baufortschrittsstufen gemäß § 632a BGB:</p>
        <p style={{ marginBottom: '16px' }}>20 % der Gesamtauftragssumme als Anzahlung nach Vertragsschluss und vor Beginn der Montageplanung.</p>
        <p style={{ marginBottom: '16px' }}>60 % der Gesamtauftragssumme nach termingerechter Lieferung der Hauptkomponenten (Module, Wechselrichter, Speicher) an den Montageort.</p>
        <p style={{ marginBottom: '16px' }}>20 % der Gesamtauftragssumme nach betriebsfertiger Montage und erfolgter technischer Inbetriebsetzung.</p>
        <p style={{ marginBottom: '16px' }}>Rechnungsbeträge sind ohne jeden Abzug innerhalb von 14 Tagen ab Rechnungsdatum zur Zahlung fällig.</p>
        <p style={{ marginBottom: '16px' }}>Gerät der Auftraggeber in Zahlungsverzug, ist der Auftragnehmer berechtigt, Verzugszinsen in gesetzlicher Höhe von fünf Prozentpunkten über dem Basiszinssatz (§ 288 Abs. 1 BGB) geltend zu machen.</p>
        <h3 style={{ fontSize: '22px', fontWeight: 800, marginTop: '40px', marginBottom: '12px', color: '#0E2841' }}>§ 5 Mitwirkungspflichten und bauseitige Voraussetzungen</h3>
        <p style={{ fontSize: '13px', fontStyle: 'italic', color: '#64748B', marginBottom: '16px' }}>(Rechtsgrundlage: §§ 642, 643 BGB)</p>
        <p style={{ marginBottom: '16px' }}>Der Auftraggeber versichert, dass das Gebäude und die Dachkonstruktion für die statische Last der Anlage sowie für die Wind- und Schneelasten am Standort geeignet sind. Eine Prüfung der statischen Gebäudesicherheit ist nicht Bestandteil der regulären Leistung, es sei denn, eine gesonderte statische Begutachtung wurde ausdrücklich vertraglich vereinbart.</p>
        <p style={{ marginBottom: '16px' }}>Der Auftraggeber stellt sicher, dass der bestehende Zählerschrank und die Hauselektrik den aktuellen technischen Anschlussbedingungen (TAB) des Netzbetreibers entsprechen. Sollten bauliche Anpassungen, Umbauten oder ein Austausch des Zählerschranks erforderlich sein, sind diese gesondert zu beauftragen und zu vergüten, sofern sie nicht ausdrücklich im Pauschalpreis enthalten sind.</p>
        <p style={{ marginBottom: '16px' }}>Der Auftraggeber gewährleistet den freien, gefahrlosen Zugang zum Montageort (Dach, Zählerplatz, Trassenverlegung) sowie die kostenfreie Bereitstellung von Baustrom und Bauwasser für die Dauer der Montage.</p>
        <p style={{ marginBottom: '16px' }}>Unterlässt der Auftraggeber eine ihm obliegende Mitwirkungshandlung, so ist der Auftragnehmer berechtigt, eine angemessene Entschädigung nach Maßgabe des § 642 BGB zu verlangen und nach Fristsetzung vom Vertrag zurückzutreten (§ 643 BGB).</p>
        <h3 style={{ fontSize: '22px', fontWeight: 800, marginTop: '40px', marginBottom: '12px', color: '#0E2841' }}>§ 6 Netzanschluss und Genehmigungen</h3>
        <p style={{ fontSize: '13px', fontStyle: 'italic', color: '#64748B', marginBottom: '16px' }}>(Rechtsgrundlage: § 8 EEG, § 19 NAV)</p>
        <p style={{ marginBottom: '16px' }}>Der Auftragnehmer unterstützt den Auftraggeber bei der Netzanmeldung und Zusammenstellung der erforderlichen Unterlagen gegenüber dem zuständigen Verteilnetzbetreiber (VNB).</p>
        <p style={{ marginBottom: '16px' }}>Der physische Netzanschluss, die Genehmigung des Netzanschlussbegehrens sowie der Zählertausch liegen in der ausschließlichen Zuständigkeit des VNB. Verzögerungen, Terminverschiebungen oder Anschlussvorgaben des VNB begründen keinen Verzug des Auftragnehmers.</p>
        <p style={{ marginBottom: '16px' }}>Sämtliche Anschluss-, Prüf- oder Zählgebühren des Netzbetreibers sind vom Auftraggeber unmittelbar an diesen zu entrichten.</p>
        <h3 style={{ fontSize: '22px', fontWeight: 800, marginTop: '40px', marginBottom: '12px', color: '#0E2841' }}>§ 7 Abnahme der Werkleistung</h3>
        <p style={{ fontSize: '13px', fontStyle: 'italic', color: '#64748B', marginBottom: '16px' }}>(Rechtsgrundlage: § 640 BGB, § 641 BGB)</p>
        <p style={{ marginBottom: '16px' }}>Nach Fertigstellung der Montage und technischer Betriebsbereitschaft ist der Auftraggeber verpflichtet, das Werk unverzüglich abzunehmen. Über die Abnahme ist ein gemeinsames Abnahmeprotokoll zu erstellen und von beiden Parteien zu unterzeichnen.</p>
        <p style={{ marginBottom: '16px' }}>Wegen unwesentlicher Mängel kann die Abnahme nicht verweigert werden (§ 640 Abs. 1 Satz 2 BGB).</p>
        <p style={{ marginBottom: '16px' }}>Hat der Auftragnehmer dem Auftraggeber nach Fertigstellung der Montage eine angemessene Frist zur Abnahme gesetzt und hat der Auftraggeber die Abnahme nicht innerhalb dieser Frist unter Angabe mindestens eines Mangels verweigert, gilt das Werk als abgenommen (§ 640 Abs. 2 BGB). Ebenso gilt die schlüssige Inbetriebnahme oder bestimmungsgemäße Nutzung durch den Auftraggeber nach Ablauf von 12 Werktagen als Abnahme.</p>
        <h3 style={{ fontSize: '22px', fontWeight: 800, marginTop: '40px', marginBottom: '12px', color: '#0E2841' }}>§ 8 Eigentumsvorbehalt</h3>
        <p style={{ fontSize: '13px', fontStyle: 'italic', color: '#64748B', marginBottom: '16px' }}>(Rechtsgrundlage: § 449 BGB, §§ 946, 951 BGB)</p>
        <p style={{ marginBottom: '16px' }}>Die gelieferten Materialien, Komponenten und Anlagenteile bleiben bis zur vollständigen Erfüllung sämtlicher Zahlungsverpflichtungen aus diesem Vertrag Eigentum des Auftragnehmers (§ 449 BGB).</p>
        <p style={{ marginBottom: '16px' }}>Eine Verbindung der Komponenten mit dem Bauwerk erfolgt vor vollständiger Kaufpreiszahlung nur zu einem vorübergehenden Zweck im Sinne des § 95 BGB (Scheinbestandteil).</p>
        <h3 style={{ fontSize: '22px', fontWeight: 800, marginTop: '40px', marginBottom: '12px', color: '#0E2841' }}>§ 9 Mängelansprüche (Gewährleistung) und Garantien</h3>
        <p style={{ fontSize: '13px', fontStyle: 'italic', color: '#64748B', marginBottom: '16px' }}>(Rechtsgrundlage: §§ 634 ff. BGB, § 634a BGB, § 443 BGB)</p>
        <p style={{ marginBottom: '16px' }}>Dem Auftraggeber stehen bei Mängeln die gesetzlichen Gewährleistungsrechte nach §§ 634 ff. BGB zu.</p>
        <p style={{ marginBottom: '16px' }}>Handelt es sich um Arbeiten an einem Bauwerk (Festinstallation auf dem Hausdach oder Wandmontage), verjähren Mängelansprüche in fünf Jahren ab Abnahme (§ 634a Abs. 1 Nr. 2 BGB).</p>
        <p style={{ marginBottom: '16px' }}>Etwaige Herstellergarantien (z. B. Produkt- oder lineare Leistungsgarantien für Solarmodule und Wechselrichter über 10, 25 oder 30 Jahre) stellen selbständige Garantiezusagen der Hersteller dar (§ 443 BGB). Der Auftragnehmer haftet nicht für die Erfüllung dieser Garantieversprechen durch Dritte.</p>
        <h3 style={{ fontSize: '22px', fontWeight: 800, marginTop: '40px', marginBottom: '12px', color: '#0E2841' }}>§ 10 Haftungsbegrenzung</h3>
        <p style={{ fontSize: '13px', fontStyle: 'italic', color: '#64748B', marginBottom: '16px' }}>(Rechtsgrundlage: § 307 BGB, § 309 Nr. 7 BGB, ProdHaftG)</p>
        <p style={{ marginBottom: '16px' }}>Der Auftragnehmer haftet unbeschränkt für Schäden aus der Verletzung des Lebens, des Körpers oder der Gesundheit, die auf einer vorsätzlichen oder fahrlässigen Pflichtverletzung beruhen.</p>
        <p style={{ marginBottom: '16px' }}>Der Auftragnehmer haftet ferner unbeschränkt für Schäden, die auf Vorsatz oder grober Fahrlässigkeit beruhen, sowie bei Ansprüchen nach dem Produkthaftungsgesetz.</p>
        <p style={{ marginBottom: '16px' }}>Bei der leicht fahrlässigen Verletzung von Kardinalpflichten (wesentliche Vertragspflichten, deren Erfüllung die ordnungsgemäße Durchführung des Vertrages überhaupt erst ermöglicht und auf deren Einhaltung der Vertragspartner regelmäßig vertrauen darf) ist die Haftung auf den vorhersehbaren, vertragstypischen Schaden begrenzt.</p>
        <p style={{ marginBottom: '16px' }}>Im Übrigen ist die Haftung für leichte Fahrlässigkeit ausgeschlossen.</p>
        <h3 style={{ fontSize: '22px', fontWeight: 800, marginTop: '40px', marginBottom: '12px', color: '#0E2841' }}>§ 11 Gesetzliche Widerrufsbelehrung für Verbraucher</h3>
        <p style={{ fontSize: '13px', fontStyle: 'italic', color: '#64748B', marginBottom: '16px' }}>(Rechtsgrundlage: § 312g BGB i. V. m. § 355 BGB, Art. 246a EGBGB)</p>
        <h4 style={{ fontSize: '18px', fontWeight: 700, marginTop: '24px', marginBottom: '12px', color: '#0E2841' }}>Widerrufsbelehrung</h4>
        <h4 style={{ fontSize: '18px', fontWeight: 700, marginTop: '24px', marginBottom: '12px', color: '#0E2841' }}>Widerrufsrecht</h4>
        <p style={{ marginBottom: '16px' }}>Sie haben das Recht, binnen vierzehn Tagen ohne Angabe von Gründen diesen Vertrag zu widerrufen.</p>
        <p style={{ marginBottom: '16px' }}>Die Widerrufsfrist beträgt vierzehn Tage ab dem Tag des Vertragsabschlusses.</p>
        <p style={{ marginBottom: '16px' }}>Um Ihr Widerrufsrecht auszuüben, müssen Sie uns:</p>
        <p style={{ marginBottom: '4px' }}>Goldy Solar GmbH</p>
        <p style={{ marginBottom: '4px' }}>Rudolf-Diesel-Straße 11, 69115 Heidelberg, Deutschland</p>
        <p style={{ marginBottom: '4px' }}>Telefon: +49 6221 502 6666</p>
        <p style={{ marginBottom: '4px' }}>E-Mail: info@goldysolar.de</p>
        <p style={{ marginBottom: '16px' }}>mittels einer eindeutigen Erklärung (z. B. ein mit der Post versandter Brief oder eine E-Mail) über Ihren Entschluss, diesen Vertrag zu widerrufen, informieren. Sie können dafür das beigefügte Muster-Widerrufsformular verwenden, das jedoch nicht vorgeschrieben ist.</p>
        <p style={{ marginBottom: '16px' }}>Zur Wahrung der Widerrufsfrist reicht es aus, dass Sie die Mitteilung über die Ausübung des Widerrufsrechts vor Ablauf der Widerrufsfrist absenden.</p>
        <h4 style={{ fontSize: '18px', fontWeight: 700, marginTop: '24px', marginBottom: '12px', color: '#0E2841' }}>Folgen des Widerrufs</h4>
        <p style={{ marginBottom: '16px' }}>Wenn Sie diesen Vertrag widerrufen, haben wir Ihnen alle Zahlungen, die wir von Ihnen erhalten haben, einschließlich der Lieferkosten (mit Ausnahme der zusätzlichen Kosten, die sich daraus ergeben, dass Sie eine andere Art der Lieferung als die von uns angebotene, günstigste Standardlieferung gewählt haben), unverzüglich und spätestens binnen vierzehn Tagen ab dem Tag zurückzuzahlen, an dem die Mitteilung über Ihren Widerruf dieses Vertrags bei uns eingegangen ist. Für diese Rückzahlung verwenden wir dasselbe Zahlungsmittel, das Sie bei der ursprünglichen Transaktion eingesetzt haben, es sei denn, mit Ihnen wurde ausdrücklich etwas anderes vereinbart; in keinem Fall werden Ihnen wegen dieser Rückzahlung Entgelte berechnet.</p>
        <p style={{ marginBottom: '16px' }}>Haben Sie verlangt, dass die Erbringung von Dienstleistungen oder Montagearbeiten während der Widerrufsfrist beginnen soll, so haben Sie uns einen angemessenen Betrag zu zahlen, der dem Anteil der bis zu dem Zeitpunkt, zu dem Sie uns von der Ausübung des Widerrufsrechts hinsichtlich dieses Vertrags unterrichten, bereits erbrachten Dienstleistungen im Vergleich zum Gesamtumfang der im Vertrag vorgesehenen Dienstleistungen entspricht (§ 357a Abs. 2 BGB).</p>
        <h4 style={{ fontSize: '18px', fontWeight: 700, marginTop: '24px', marginBottom: '12px', color: '#0E2841' }}>Vorzeitiges Erlöschen des Widerrufsrechts</h4>
        <p style={{ marginBottom: '16px' }}>Das Widerrufsrecht erlischt bei einem Vertrag zur Erbringung von Dienstleistungen vorzeitig, wenn der Auftragnehmer die Dienstleistung vollständig erbracht hat und mit der Ausführung der Dienstleistung erst begonnen hat, nachdem der Verbraucher dazu seine ausdrückliche Zustimmung gegeben hat und gleichzeitig seine Kenntnis davon bestätigt hat, dass er sein Widerrufsrecht bei vollständiger Vertragserfüllung durch den Unternehmer verliert (§ 356 Abs. 4 BGB).</p>
        <h4 style={{ fontSize: '18px', fontWeight: 700, marginTop: '24px', marginBottom: '12px', color: '#0E2841' }}>Muster-Widerrufsformular</h4>
        <p style={{ fontSize: '13px', fontStyle: 'italic', color: '#64748B', marginBottom: '16px' }}>(Rechtsgrundlage: Anlage 2 zu Art. 246a § 1 Abs. 2 Satz 1 Nr. 1 EGBGB)</p>
        <p style={{ marginBottom: '16px' }}>(Wenn Sie den Vertrag widerrufen wollen, dann füllen Sie bitte dieses Formular aus und senden Sie es zurück.)</p>
        <p style={{ marginBottom: '16px' }}>An: Goldy Solar GmbH, Rudolf-Diesel-Straße 11, 69115 Heidelberg, E-Mail: info@goldysolar.de</p>
        <p style={{ marginBottom: '16px' }}>Hiermit widerrufe(n) ich/wir (*) den von mir/uns (*) abgeschlossenen Vertrag über den Kauf der folgenden Waren (*) / die Erbringung der folgenden Dienstleistung (*):</p>
        <p style={{ marginBottom: '16px' }}>Bestellt am (*) / erhalten am (*):</p>
        <p style={{ marginBottom: '16px' }}>Name des/der Verbraucher(s):</p>
        <p style={{ marginBottom: '16px' }}>Anschrift des/der Verbraucher(s):</p>
        <p style={{ marginBottom: '16px' }}>Unterschrift des/der Verbraucher(s) (nur bei Mitteilung auf Papier):</p>
        <p style={{ marginBottom: '16px' }}>Datum:</p>
        <p style={{ marginBottom: '16px' }}>(*) Unzutreffendes streichen.</p>
        <h3 style={{ fontSize: '22px', fontWeight: 800, marginTop: '40px', marginBottom: '12px', color: '#0E2841' }}>§ 12 Streitbeilegung und Schlussbestimmungen</h3>
        <p style={{ fontSize: '13px', fontStyle: 'italic', color: '#64748B', marginBottom: '16px' }}>(Rechtsgrundlage: § 36 VSBG, § 306 BGB)</p>
        <p style={{ marginBottom: '16px' }}>Die Europäische Kommission stellt eine Plattform zur Online-Streitbeilegung (OS) bereit, die unter https://ec.europa.eu/consumers/odr aufrufbar ist.</p>
        <p style={{ marginBottom: '16px' }}>Der Auftragnehmer ist nicht bereit und nicht verpflichtet, an einem Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle im Sinne des Verbraucherstreitbeilegungsgesetzes (VSBG) teilzunehmen (§ 36 VSBG).</p>
        <p style={{ marginBottom: '16px' }}>Es gilt das Recht der Bundesrepublik Deutschland unter Ausschluss des UN-Kaufrechts (CISG).</p>
        <p style={{ marginBottom: '16px' }}>Erfüllungsort für alle Lieferungen und Leistungen ist der im Vertrag festgelegte Montageort; für Zahlungsverbindlichkeiten der Sitz des Auftragnehmers.</p>
        <p style={{ marginBottom: '16px' }}>Sollten einzelne Bestimmungen dieses Vertrages ganz oder teilweise unwirksam sein oder werden, bleibt die Gültigkeit der übrigen Bestimmungen hiervon unberührt (§ 306 Abs. 1 BGB).</p>
        <hr style={{ margin: '40px 0', borderColor: '#CBD5E1' }} />
        <h2 style={{ fontSize: '28px', fontWeight: 900, marginTop: '60px', marginBottom: '20px', color: '#0F4761' }}>Allgemeine Geschäftsbedingungen für Unternehmer und Firmenkunden (B2B)</h2>
        <p style={{ fontSize: '18px', fontWeight: 700, marginBottom: '30px', color: '#4285F4' }}>für Planung, Beschaffung, Errichtung (EPC) und Montage von gewerblichen Photovoltaikanlagen, Großspeichern und Ladeinfrastruktur</p>
        <h3 style={{ fontSize: '22px', fontWeight: 800, marginTop: '40px', marginBottom: '12px', color: '#0E2841' }}>§ 1 Geltungsbereich und Ausschluss fremder AGB</h3>
        <p style={{ fontSize: '13px', fontStyle: 'italic', color: '#64748B', marginBottom: '16px' }}>(Rechtsgrundlage: § 14 BGB, §§ 305 ff. BGB)</p>
        <p style={{ marginBottom: '16px' }}>Diese Allgemeinen Geschäftsbedingungen gelten für alle gegenwärtigen und zukünftigen Geschäftsbeziehungen zwischen der Goldy Solar GmbH (nachfolgend „Auftragnehmer“) und ihren Kunden (nachfolgend „Auftraggeber“) über gewerbliche Photovoltaik-Großanlagen, C&amp;I-Dachanlagen, Freiflächenanlagen, Ladeinfrastruktur sowie damit verbundene EPC- und Installationsleistungen.</p>
        <p style={{ marginBottom: '16px' }}>Der Auftraggeber bestätigt, dass er den Vertrag ausschließlich in Ausübung seiner gewerblichen oder selbständigen beruflichen Tätigkeit schließt (§ 14 BGB) oder als juristische Person des öffentlichen Rechts bzw. öffentlich-rechtliches Sondervermögen handelt. Ein gesetzliches Widerrufsrecht für Verbraucher (§§ 312g, 355 BGB) besteht nicht.</p>
        <p style={{ marginBottom: '16px' }}>Entgegenstehende, abweichende oder ergänzende Bedingungen des Auftraggebers werden selbst bei Kenntnis nicht Vertragsbestandteil, es sei denn, ihrer Geltung wird ausdrücklich schriftlich zugestimmt. Die widerspruchslose Annahme von Lieferungen oder Leistungen stellt keine Zustimmung dar.</p>
        <h3 style={{ fontSize: '22px', fontWeight: 800, marginTop: '40px', marginBottom: '12px', color: '#0E2841' }}>§ 2 Vertragsschluss, Bindefrist und Unterlagen</h3>
        <p style={{ fontSize: '13px', fontStyle: 'italic', color: '#64748B', marginBottom: '16px' }}>(Rechtsgrundlage: §§ 145, 147 BGB, § 312i Abs. 2 Nr. 1 BGB)</p>
        <p style={{ marginBottom: '16px' }}>Angebote des Auftragnehmers sind freibleibend, sofern sie nicht ausdrücklich als verbindlich gekennzeichnet sind.</p>
        <p style={{ marginBottom: '16px' }}>Verbindliche Angebote sind – mangels abweichender Vereinbarung – 14 Tage ab Ausstellungsdatum bindend.</p>
        <p style={{ marginBottom: '16px' }}>Technische Unterlagen, Zeichnungen, statische Grobberechnungen und Ertragssimulationen (z. B. PVsyst, PV*SOL) bleiben geistiges Eigentum des Auftragnehmers und dürfen Dritten ohne vorherige schriftliche Zustimmung nicht zugänglich gemacht werden (§§ 17, 18 GeschGehG).</p>
        <p style={{ marginBottom: '16px' }}>Die Vorschriften des § 312i Abs. 1 Satz 1 Nr. 1 bis 3 BGB (elektronischer Geschäftsverkehr) werden gemäß § 312i Abs. 2 Satz 1 BGB ausdrücklich abbedungen.</p>
        <h3 style={{ fontSize: '22px', fontWeight: 800, marginTop: '40px', marginBottom: '12px', color: '#0E2841' }}>§ 3 Preise, Steuern und Zahlungsbedingungen</h3>
        <p style={{ fontSize: '13px', fontStyle: 'italic', color: '#64748B', marginBottom: '16px' }}>(Rechtsgrundlage: § 271 BGB, § 288 Abs. 2 und Abs. 5 BGB)</p>
        <p style={{ marginBottom: '16px' }}>Alle Preise verstehen sich in Euro rein netto zuzüglich der gesetzlich anfallenden Umsatzsteuer in jeweils geltender Höhe.</p>
        <p style={{ marginBottom: '16px' }}>Das Vorliegen der Voraussetzungen für Steuerbefreiungen oder Steuerermäßigungen ist vom Auftraggeber vor Auftragserteilung nachzuweisen. Liegen diese nicht vor, wird die Regelbesteuerung (19 %) angewendet.</p>
        <p style={{ marginBottom: '16px' }}>Soweit vertraglich nicht abweichend vereinbart, gelten folgende Fälligkeitsstufen:</p>
        <p style={{ marginBottom: '16px' }}>30 % Anzahlung bei Auftragserteilung und vor Freigabe der Werk- und Montageplanung,</p>
        <p style={{ marginBottom: '16px' }}>50 % Zwischenzahlung bei Anlieferung der Hauptkomponenten (Module, Wechselrichter, Trafos) am Einsatzort,</p>
        <p style={{ marginBottom: '16px' }}>20 % Schlusszahlung nach technischer Fertigstellung und VNB-Meldung.</p>
        <p style={{ marginBottom: '16px' }}>Rechnungen sind innerhalb von 14 Tagen nach Rechnungsdatum rein netto zahlbar.</p>
        <p style={{ marginBottom: '16px' }}>Bei Überschreitung des Zahlungsziels gerät der Auftraggeber ohne gesonderte Mahnung in Verzug. Der Verzugszinssatz beträgt neun Prozentpunkte über dem jeweiligen Basiszinssatz (§ 288 Abs. 2 BGB). Der Auftragnehmer behält sich vor, den gesetzlichen Pauschalschadensersatz in Höhe von 40 Euro geltend zu machen (§ 288 Abs. 5 BGB).</p>
        <h3 style={{ fontSize: '22px', fontWeight: 800, marginTop: '40px', marginBottom: '12px', color: '#0E2841' }}>§ 4 Bauseitige Voraussetzungen, Statik und Mitwirkung</h3>
        <p style={{ fontSize: '13px', fontStyle: 'italic', color: '#64748B', marginBottom: '16px' }}>(Rechtsgrundlage: § 642 BGB, § 645 BGB)</p>
        <p style={{ marginBottom: '16px' }}>Der Auftraggeber ist vollumfänglich dafür verantwortlich, dass die Bausubstanz, Tragwerke, Dachhaut und Fundamente für die zusätzlichen Lasten (Eigenlast, Wind- und Schneelasten) statisch geeignet und dauerhaft standfest sind. Der statische Nachweis ist vom Auftraggeber auf eigene Kosten beizubringen.</p>
        <p style={{ marginBottom: '16px' }}>Der Auftraggeber stellt sicher, dass rechtzeitig vor Baubeginn:</p>
        <p style={{ marginBottom: '16px' }}>Zufahrten für Schwertransporte, Kräne und Montagefahrzeuge befahrbar und lastfähig sind,</p>
        <p style={{ marginBottom: '16px' }}>Lagerflächen und Montageplätze trocken, befestigt und ausreichend gesichert zur Verfügung stehen,</p>
        <p style={{ marginBottom: '16px' }}>Wasser- und Stromanschlüsse in benötigter Dimension kostenfrei am Installationsort anliegen.</p>
        <p style={{ marginBottom: '16px' }}>Erfordert die Einspeisung den Bau oder Umbau einer Mittelspannungsstation, von Transformatoren oder Trassen auf dem Grundstück des Auftraggebers, hat dieser alle hierfür erforderlichen Leitungsrechte, Baulasten und Dienstbarkeiten kosten- und lastenfrei einzuräumen.</p>
        <p style={{ marginBottom: '16px' }}>Kommt der Auftraggeber seinen Mitwirkungspflichten nicht nach, trägt er die hierdurch entstehenden Mehraufwände, Stillstandszeiten und Gerüstkosten gemäß § 642 BGB.</p>
        <h3 style={{ fontSize: '22px', fontWeight: 800, marginTop: '40px', marginBottom: '12px', color: '#0E2841' }}>§ 5 Lieferfristen, Montage und Höhere Gewalt</h3>
        <p style={{ fontSize: '13px', fontStyle: 'italic', color: '#64748B', marginBottom: '16px' }}>(Rechtsgrundlage: § 275 BGB, § 313 BGB)</p>
        <p style={{ marginBottom: '16px' }}>Vereinbarte Fristen und Termine sind Richtwerte, es sei denn, ein Termin wurde ausdrücklich als verbindlicher Fixtermin vereinbart.</p>
        <p style={{ marginBottom: '16px' }}>Die Liefer- und Leistungsfristen verlängern sich angemessen beim Eintritt unvorhersehbarer, außergewöhnlicher Ereignisse, die der Auftragnehmer trotz zumutbarer Sorgfalt nicht abwenden konnte (höhere Gewalt, Krieg, Streik, behördliche Eingriffe, extreme Witterungsbedingungen, Rohstoffengpässe sowie Lieferausfälle von Komponentenherstellern).</p>
        <p style={{ marginBottom: '16px' }}>Entstehen Verzögerungen durch die Netzanschlussprüfung oder Zuweisung des Netzverknüpfungspunktes durch den zuständigen Verteilnetzbetreiber (VNB), ist eine Verzugshaftung des Auftragnehmers insoweit ausgeschlossen.</p>
        <h3 style={{ fontSize: '22px', fontWeight: 800, marginTop: '40px', marginBottom: '12px', color: '#0E2841' }}>§ 6 Rügepflicht und Abnahme im kaufmännischen Verkehr</h3>
        <p style={{ fontSize: '13px', fontStyle: 'italic', color: '#64748B', marginBottom: '16px' }}>(Rechtsgrundlage: § 377 HGB, § 640 BGB)</p>
        <p style={{ marginBottom: '16px' }}>Untersuchungs- und Rügepflicht (§ 377 HGB): Der Auftraggeber hat gelieferte Materialien und Komponenten unverzüglich nach Eintreffen auf Vollständigkeit, Transportschäden und offensichtliche Mängel zu untersuchen. Offensichtliche Mängel sind binnen fünf Werktagen schriftlich und spezifiziert anzuzeigen. Versteckte Mängel sind unverzüglich nach deren Entdeckung anzuzeigen. Unterbleibt die rechtzeitige Rüge, gilt die Ware in Ansehung des Mangels als genehmigt.</p>
        <p style={{ marginBottom: '16px' }}>Nach Fertigstellung der Montage und technischer Betriebsbereitschaft erfolgt eine gemeinsame förmliche Abnahme. Über das Ergebnis ist ein Abnahmeprotokoll zu fertigen.</p>
        <p style={{ marginBottom: '16px' }}>Wegen unwesentlicher Mängel kann die Abnahme nicht verweigert werden.</p>
        <p style={{ marginBottom: '16px' }}>Die Anlage gilt als abgenommen, wenn der Auftragnehmer nach Fertigstellung eine angemessene Frist zur Abnahme gesetzt hat und der Auftraggeber die Abnahme nicht innerhalb dieser Frist unter Angabe konkreter wesentlicher Mängel verweigert hat (§ 640 Abs. 2 BGB), spätestens jedoch mit der Inbetriebnahme oder Netzeinspeisung.</p>
        <h3 style={{ fontSize: '22px', fontWeight: 800, marginTop: '40px', marginBottom: '12px', color: '#0E2841' }}>§ 7 Erweiterter und verlängerter Eigentumsvorbehalt</h3>
        <p style={{ fontSize: '13px', fontStyle: 'italic', color: '#64748B', marginBottom: '16px' }}>(Rechtsgrundlage: § 449 BGB, § 398 BGB, §§ 946 ff. BGB)</p>
        <p style={{ marginBottom: '16px' }}>Die gelieferte Ware bleibt bis zur vollständigen Erfüllung sämtlicher bestehender und künftiger Forderungen aus der laufenden Geschäftsbeziehung Eigentum des Auftragnehmers.</p>
        <p style={{ marginBottom: '16px' }}>Wird die Vorbehaltsware mit einem Gebäude fest verbunden, so geschieht dies lediglich zu einem vorübergehenden Zweck gemäß § 95 BGB (Scheinbestandteil).</p>
        <p style={{ marginBottom: '16px' }}>Für den Fall der Weiterveräußerung der Vorbehaltsware im ordnungsgemäßen Geschäftsbetrieb tritt der Auftraggeber bereits jetzt alle daraus resultierenden Forderungen in Höhe des Rechnungsendbetrags an den Auftragnehmer ab (verlängerter Eigentumsvorbehalt). Der Auftragnehmer nimmt die Abtretung an.</p>
        <h3 style={{ fontSize: '22px', fontWeight: 800, marginTop: '40px', marginBottom: '12px', color: '#0E2841' }}>§ 8 Gewährleistung (Sachmängelansprüche)</h3>
        <p style={{ fontSize: '13px', fontStyle: 'italic', color: '#64748B', marginBottom: '16px' }}>(Rechtsgrundlage: § 437 BGB, § 634 BGB, § 634a BGB)</p>
        <p style={{ marginBottom: '16px' }}>Bei Vorliegen eines Mangels ist der Auftragnehmer nach eigener Wahl zur Nacherfüllung durch Beseitigung des Mangels oder Lieferung einer mangelfreien Sache berechtigt (§ 635 BGB).</p>
        <p style={{ marginBottom: '16px' }}>Die Verjährungsfrist für Sachmängelansprüche beträgt – abweichend von den gesetzlichen Fristen – ein Jahr ab Abnahme bzw. Gefahrübergang.</p>
        <p style={{ marginBottom: '16px' }}>Die vorstehende Fristverkürzung gilt nicht für:</p>
        <p style={{ marginBottom: '16px' }}>Werkleistungen, die entsprechend ihrer üblichen Verwendungsweise für ein Bauwerk verwendet worden sind und dessen Mangelhaftigkeit verursacht haben (§ 634a Abs. 1 Nr. 2 BGB),</p>
        <p style={{ marginBottom: '16px' }}>vorsätzliche oder arglistig verschwiegene Mängel (§ 634a Abs. 3 BGB).</p>
        <p style={{ marginBottom: '16px' }}>Soweit Hersteller von Modulen, Wechselrichtern oder Speicherblöcken über die Gewährleistung hinausgehende Garantien einräumen, handelt es sich um reine Herstellergarantien. Der Auftragnehmer übernimmt für deren Durchsetzbarkeit keine Gewähr.</p>
        <h3 style={{ fontSize: '22px', fontWeight: 800, marginTop: '40px', marginBottom: '12px', color: '#0E2841' }}>§ 9 Haftung und Haftungsbegrenzung</h3>
        <p style={{ fontSize: '13px', fontStyle: 'italic', color: '#64748B', marginBottom: '16px' }}>(Rechtsgrundlage: §§ 280, 276 BGB, § 307 BGB, ProdHaftG)</p>
        <p style={{ marginBottom: '16px' }}>Der Auftragnehmer haftet unbeschränkt für Schäden an Leben, Körper oder Gesundheit, bei Vorsatz und grober Fahrlässigkeit, bei Arglist sowie nach dem Produkthaftungsgesetz.</p>
        <p style={{ marginBottom: '16px' }}>Bei einfacher Fahrlässigkeit haftet der Auftragnehmer nur für die Verletzung wesentlicher Vertragspflichten (Kardinalpflichten). In diesem Fall ist die Haftung auf den typischen, bei Vertragsschluss vorhersehbaren Schaden begrenzt.</p>
        <p style={{ marginBottom: '16px' }}>Die Haftung für mittelbare Schäden, entgangenen Gewinn, Betriebsunterbrechungen sowie Ausfall von Einspeisevergütungen ist bei einfacher Fahrlässigkeit vollumfänglich ausgeschlossen.</p>
        <p style={{ marginBottom: '16px' }}>Soweit die Haftung ausgeschlossen oder begrenzt ist, gilt dies auch für die persönliche Haftung von Organen, Vertretern, Erfüllungsgehilfen und Subunternehmern des Auftragnehmers (§ 278 BGB).</p>
        <h3 style={{ fontSize: '22px', fontWeight: 800, marginTop: '40px', marginBottom: '12px', color: '#0E2841' }}>§ 10 Anwendbares Recht, Erfüllungsort und Gerichtsstand</h3>
        <p style={{ fontSize: '13px', fontStyle: 'italic', color: '#64748B', marginBottom: '16px' }}>(Rechtsgrundlage: § 38 ZPO, § 29 ZPO)</p>
        <p style={{ marginBottom: '16px' }}>Es gilt ausschließlich das Recht der Bundesrepublik Deutschland unter Ausschluss des Übereinkommens der Vereinten Nationen über Verträge über den internationalen Warenkauf (CISG).</p>
        <p style={{ marginBottom: '16px' }}>Erfüllungsort für alle Lieferungen und Leistungen ist der im Vertrag festgelegte Montageort; für Zahlungsverbindlichkeiten der Sitz des Auftragnehmers.</p>
        <p style={{ marginBottom: '16px' }}>Ausschließlicher Gerichtsstand für alle Streitigkeiten aus oder im Zusammenhang mit diesem Vertrag ist der Sitz der Goldy Solar GmbH (Heidelberg / Amtsgericht Mannheim bzw. Landgericht Heidelberg), sofern der Auftraggeber Kaufmann im Sinne des HGB, juristische Person des öffentlichen Rechts oder öffentlich-rechtliches Sondervermögen ist (§ 38 ZPO).</p>
        <p style={{ marginBottom: '16px' }}>Sollten einzelne Klauseln dieser Bedingungen unwirksam sein oder werden, berührt dies die Gültigkeit der übrigen Bestimmungen nicht (§ 306 BGB).</p>
      </div>
    </div>
  );
}
